# Generated by Django 3.1.2 on 2020-10-07 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('fail', 'Failed')], default=None, max_length=100, null=True)),
                ('reference_id', models.TextField(max_length=50, unique=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('transaction_type', models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default=None, max_length=100, null=True)),
                ('transactioned_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
